[workspace]
members = [
  "vault-core",
  "vault-core/user-error-derive",
  "vault-fake-remote",
  "vault-native",
  "vault-wasm",
]

[profile.release]
# lto = true

[profile.release.package.vault-wasm]
opt-level = "s"
