[package]
name = "vault-wasm"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
async-trait = "0.1.77"
futures = "0.3.31"
getrandom = { version = "0.2.12", features = ["js"] }
http = "0.2.11"
js-sys = "0.3.77"
log = "0.4.20"
serde = { version = "1.0.195", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
thiserror = "2.0.17"
tsify = { version = "0.5.5", features = ["js"] }
vault-core = { path = "../vault-core" }
vault-crypto = { path = "../vault-crypto" }
vault-web-api = { path = "../vault-web-api" }
vault-file-icon = { path = "../vault-file-icon", default-features = false }
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
wasm-streams = "0.4.2"
web-sys = { version = "0.3.77", features = [
  'AbortController',
  'AbortSignal',
  'Blob',
  'BlobPropertyBag',
  'console',
  'File',
  'Headers',
  'Storage',
  'ReadableStream',
  'Request',
  'RequestInit',
  'RequestMode',
  'Response',
  'Window',
] }
