[package]
name = "vault-core-tests"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = "0.1.89"
axum = { version = "0.8.8", features = ["ws", "multipart", "http2"] }
env_logger = "0.11.8"
futures = "0.3.31"
hex = "0.4.3"
log = "0.4.29"
md5 = "0.7.0"
reqwest = { version = "0.12.28", default-features = false, features = [
  "rustls-tls",
  "stream",
] }
rustls = { version = "0.23.35", default-features = false, features = [
  "std",
  "tls12",
  "ring",
] }
serde = "1.0.228"
serde_json = "1.0.147"
similar-asserts = "1.7.0"
tokio = { version = "1.48.0", features = ["full"] }
# uuid cannot be upgraded to > 1.12.1 because we cannot use rand_core > 0.6
uuid = { version = "=1.12.1", features = ["v4", "fast-rng"] }
vault-core = { path = "../vault-core" }
vault-crypto = { path = "../vault-crypto" }
vault-fake-remote = { path = "../vault-fake-remote" }
vault-native = { path = "../vault-native" }
vault-store = { path = "../vault-store" }
