[package]
name = "vault-desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.147"
tauri = { version = "2.9.5", features = [] }
tauri-plugin-dialog = "2.4.2"
tauri-plugin-shell = "2.3.3"
tokio = { version = "1.35.1", features = ["rt-multi-thread"] }
vault-core = { path = "../../vault-core" }
vault-desktop-server = { path = "../../vault-desktop-server" }
vault-native = { path = "../../vault-native" }
vault-web-api = { path = "../../vault-web-api" }

[build-dependencies]
tauri-build = { version = "2.5.3", features = [] }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
