package net.koofr.vault

object PreviewsData {
    val repos = listOf(
        Repo(
            id = "49c1953f-efb0-4b5a-bf06-02da11e2a9d6",
            name = "Vault",
            mountId = "7ac98cb0-93d6-433a-878b-fee805e9d68f",
            path = "/Vault",
            state = RepoState.UNLOCKED,
            added = 1666300393650,
            webUrl = "https://app.koofr.net/app/storage/7ac98cb0-93d6-433a-878b-fee805e9d68f?path=%2FVault",
            autoLock = RepoAutoLock(after = RepoAutoLockAfter.Inactive1Hour, onAppHidden = false),
        ),
        Repo(
            id = "ab72e550-64cf-4eaf-9f4c-4dda6459a045",
            name = "Vault 1",
            mountId = "7ac98cb0-93d6-433a-878b-fee805e9d68f",
            path = "/Vault 1",
            state = RepoState.LOCKED,
            added = 1666300428883,
            webUrl = "https://app.koofr.net/app/storage/7ac98cb0-93d6-433a-878b-fee805e9d68f?path=%2FVault%201",
            autoLock = RepoAutoLock(after = RepoAutoLockAfter.Inactive1Hour, onAppHidden = false),
        ),
    )

    val repoConfig = RepoConfig(
        name = "My safe box",
        location = RemoteFilesLocation(
            mountId = "c1450ad8-1f79-4f2f-938d-0a4bfd927313",
            path = "/My safe box",
        ),
        password = "password",
        salt = "salt",
        rcloneConfig = "[my-safe-box]\ntype=crypt\nremote=koofr:/My safe box\npassword=QRnSVJm14OpUhFyUOMjlelemU14sXMIV\npassword2=ntSsq_groe8-AMAKUEjGbapCTQU",
    )

    val repoFiles = listOf(
        RepoFile(
            id = "011a4ac4-0844-40ef-9e69-dffb45ee5aaa:/example.jpg",
            repoId = "011a4ac4-0844-40ef-9e69-dffb45ee5aaa",
            encryptedPath = "/pto9jrnh1kar26rfahf2hbu8bk",
            decryptedPath = "/example.jpg",
            name = "example example example example example example example example example.jpg",
            nameError = null,
            ext = "jpg",
            contentType = "image/jpeg",
            typ = RepoFileType.FILE,
            sizeDisplay = "128.1 KB",
            modified = 123456789,
            category = FileCategory.IMAGE,
            fileIconAttrs = FileIconAttrs(
                category = FileCategory.IMAGE,
                isDl = false,
                isUl = false,
                isDownloadTransfer = false,
                isUploadTransfer = false,
                isExport = false,
                isImport = false,
                isAndroid = false,
                isIos = false,
                isVaultRepo = false,
                isError = false,
            ),
        ),
    )

    val transfersSummary = TransfersSummary(
        totalCount = 2u,
        doneCount = 0u,
        failedCount = 0u,
        sizeProgressDisplay = "14.6 / 219.4 MB",
        percentage = 6u,
        remainingTimeDisplay = "2m 19s",
        speedDisplay = "1.5 MB/s",
        isTransferring = true,
        isAllDone = false,
        canRetryAll = false,
        canAbortAll = true,
    )

    val transfersList = listOf(
        Transfer(
            id = 0u,
            typ = TransferType.UPLOAD,
            name = "IMG_1401.mp4",
            fileIconAttrs = FileIconAttrs(
                category = FileCategory.VIDEO,
                isDl = false,
                isUl = false,
                isDownloadTransfer = false,
                isUploadTransfer = true,
                isExport = false,
                isImport = false,
                isAndroid = false,
                isIos = false,
                isVaultRepo = false,
                isError = false,
            ),
            size = 134562934,
            sizeDisplay = "128.3 MB",
            sizeProgressDisplay = "4.8 / 128.3 MB",
            percentage = 4u,
            transferredBytes = 5046272,
            transferredDisplay = "4.8 MB",
            speedDisplay = "495.1 KB/s",
            state = TransferState.Transferring,
            canRetry = false,
            canOpen = false,
        ),
        Transfer(
            id = 1u,
            typ = TransferType.DOWNLOAD,
            name = "Report 2023.pdf",
            fileIconAttrs = FileIconAttrs(
                category = FileCategory.PDF,
                isDl = false,
                isUl = false,
                isDownloadTransfer = true,
                isUploadTransfer = false,
                isExport = false,
                isImport = false,
                isAndroid = false,
                isIos = false,
                isVaultRepo = false,
                isError = false,
            ),
            size = 95514160,
            sizeDisplay = "91.1 MB",
            sizeProgressDisplay = "9.9 / 91.1 MB",
            percentage = 11u,
            transferredBytes = 10354688,
            transferredDisplay = "9.9 MB",
            speedDisplay = "1.3 MB/s",
            state = TransferState.Transferring,
            canRetry = false,
            canOpen = false,
        ),
        Transfer(
            id = 2u,
            typ = TransferType.UPLOAD,
            name = "Documents.zip",
            fileIconAttrs = FileIconAttrs(
                category = FileCategory.ARCHIVE,
                isDl = false,
                isUl = false,
                isDownloadTransfer = false,
                isUploadTransfer = true,
                isExport = false,
                isImport = false,
                isAndroid = false,
                isIos = false,
                isVaultRepo = false,
                isError = false,
            ),
            size = 10485760,
            sizeDisplay = "10 MB",
            sizeProgressDisplay = "0 / 10 MB",
            percentage = 0u,
            transferredBytes = 0,
            transferredDisplay = "0 MB",
            speedDisplay = "0 MB/s",
            state = TransferState.Failed("Unknown error"),
            canRetry = true,
            canOpen = false,
        ),
        Transfer(
            id = 3u,
            typ = TransferType.DOWNLOAD,
            name = "Photo.jpg",
            fileIconAttrs = FileIconAttrs(
                category = FileCategory.IMAGE,
                isDl = false,
                isUl = false,
                isDownloadTransfer = true,
                isUploadTransfer = false,
                isExport = false,
                isImport = false,
                isAndroid = false,
                isIos = false,
                isVaultRepo = false,
                isError = false,
            ),
            size = 1354936,
            sizeDisplay = "1.29 MB",
            sizeProgressDisplay = "1.29 / 1.29 MB",
            percentage = 100u,
            transferredBytes = 1354936,
            transferredDisplay = "1.29 MB",
            speedDisplay = null,
            state = TransferState.Done,
            canRetry = false,
            canOpen = true,
        ),
    )
}
