[package]
name = "vault-native"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = "0.1.89"
futures = "0.3.31"
http = "1.4.0"
log = "0.4.29"
reqwest = { version = "0.12.28", default-features = false, features = [
  "rustls-tls",
  "stream",
] }
tokio = { version = "1.35.1", features = ["full"] }
tokio-tungstenite = { version = "0.28.0", features = [
  "rustls-tls-webpki-roots",
] }
tokio-util = { version = "0.7.9", features = ["compat"] }
# uuid cannot be upgraded to > 1.12.1 because we cannot use rand_core > 0.6
uuid = { version = "=1.12.1", features = ["v4", "fast-rng"] }
vault-core = { path = "../vault-core" }
vault-crypto = { path = "../vault-crypto" }
rustls = { version = "0.23.35", default-features = false, features = [
  "std",
  "tls12",
  "ring",
] }

[dev-dependencies]
env_logger = "0.11.0"
similar-asserts = "1.5.0"
