name: build-vault-android

on: push

jobs:
  build-vault-android:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 10406996
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: false
      - name: Setup Android NDK
        run: |
          sdkmanager "ndk;26.0.10792818"
      - uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: "cargo-registry-${{ hashFiles('**/Cargo.lock') }}"
      - uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: "cargo-index-${{ hashFiles('**/Cargo.lock') }}"
      - uses: actions/cache@v3
        with:
          path: target
          key: cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
      - name: Install rust
        uses: dtolnay/rust-toolchain@b44cb146d03e8d870c57ab64b80f04586349ca5d
        with:
          toolchain: "1.75.0"
          targets: aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android
      - name: Build vault-android
        run: |
          cd vault-android
          echo 'sdk.dir=/usr/local/lib/android/sdk' >> local.properties
          echo 'android.ndkVersion=26.0.10792818' >> local.properties

          ./gradlew generateUniFFIBindings

          ./gradlew cargoBuild

          ./gradlew bundleRelease

          ./gradlew assembleRelease
      - uses: actions/upload-artifact@v4
        with:
          name: vault-android.aab
          path: vault-android/app/build/outputs/bundle/release/app-release.aab
          retention-days: 30
          if-no-files-found: error
      - uses: actions/upload-artifact@v4
        with:
          name: vault-android-unsigned.apk
          path: vault-android/app/build/outputs/apk/release/app-release-unsigned.apk
          retention-days: 30
          if-no-files-found: error
